name: C# App
on:
  pull_request:
    branches: [ master ]
jobs:
  run-selected-unittests:
    runs-on: windows-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    name: Run MSBuild
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.1.0
        id: checkout_code
            
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v1.0.0
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        run: |
          msbuild .\Mic_volume_freeze.sln  /t:clean /p:Configuration=Release
          nuget restore .\Mic_volume_freeze.sln
          msbuild .\Mic_volume_freeze.sln  /t:build /p:Configuration=Release
